# Name of your application. Used to uniquely configure containers.
service: resto-buzzlabs

# Name of the container image.
image: fpcarboni/astropie_ai_chat
# Deploy to these servers.
servers:
  web:
    - 161.35.53.213

proxy:
  ssl: true
  # host:
  hosts:
    - resto.buzzlabs.pt

  # Proxy connects to your container on port 80 by default.
  app_port: 3000
  healthcheck:
    path: /

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: fpcarboni

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

ssh:
  keys_only: true
  keys: [ "~/.ssh/itlabs" ]
