name: CI / Build and Push

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}

    - name: Trigger Portainer Webhook
      id: request
      uses: tyrrrz/action-http-request@master
      with:
        url: https://zapi.portainer.buzzlabs.pt/api/webhooks/826c8aa3-d08f-4019-8756-cd91bb00103f
        method: POST

    - name: Print outputs
      run: |
        echo "Status: ${{ steps.request.outputs.status }}"
        echo "Success: ${{ steps.request.outputs.success }}"
        echo "Headers: ${{ steps.request.outputs.headers }}"
        echo "Body: ${{ steps.request.outputs.body }}"
